# Generated by Django 4.0.6 on 2022-11-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
