# Generated by Django 4.0.6 on 2022-11-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('discription', models.TextField(max_length=50)),
                ('image', models.ImageField(upload_to='product')),
                ('catagory', models.ManyToManyField(to='ProductApp.catagorymodel')),
            ],
        ),
    ]
