# Generated by Django 4.0.6 on 2022-11-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0003_productmodel_price_alter_productmodel_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagorymodel',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
